from uuid import UUID

__all__ = ["install", "uninstall", "installed", "uuid6", "uuid7"]

def install() -> None: ...
def uninstall() -> None: ...
def installed() -> bool: ...
def uuid6(node: int | None = None, clock_seq: int | None = None) -> UUID: ...
def uuid7() -> UUID: ...
def reseed_rng() -> None: ...
