[package]
name = "uuideal"
version = "0.2.0"
edition = "2021"
rust-version = "1.75"
publish = false

[lib]
name = "uuideal"
crate-type = ["cdylib"]

[dependencies]
pyo3-ffi = { version = "0.28.2", features = ["extension-module", "generate-import-lib"] }
rand = "0.10.1"
uuid = { version = "1.23.1", features = ["v1", "v3", "v4", "v5", "v6", "v7", "fast-rng"] }


[build-dependencies]
pyo3-build-config = "0.28.2"

[profile.release]
lto = "fat"
codegen-units = 1
strip = "debuginfo"

[profile.dev]
incremental = true
codegen-units = 16
